//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapWebServiceTest.webService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server", ConfigurationName="webService.SoapWebServiceImpl")]
    public interface SoapWebServiceImpl {
        
        // CODEGEN: 操作 IDcardCheck 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoapWebServiceTest.webService.IDcardCheckResponse IDcardCheck(SoapWebServiceTest.webService.IDcardCheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapWebServiceTest.webService.IDcardCheckResponse> IDcardCheckAsync(SoapWebServiceTest.webService.IDcardCheckRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDcardCheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server", Order=0)]
        public string IDNum;
        
        public IDcardCheckRequest() {
        }
        
        public IDcardCheckRequest(string IDNum) {
            this.IDNum = IDNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDcardCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server", Order=0)]
        public string IDcardCheckReturn;
        
        public IDcardCheckResponse() {
        }
        
        public IDcardCheckResponse(string IDcardCheckReturn) {
            this.IDcardCheckReturn = IDcardCheckReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoapWebServiceImplChannel : SoapWebServiceTest.webService.SoapWebServiceImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapWebServiceImplClient : System.ServiceModel.ClientBase<SoapWebServiceTest.webService.SoapWebServiceImpl>, SoapWebServiceTest.webService.SoapWebServiceImpl {
        
        public SoapWebServiceImplClient() {
        }
        
        public SoapWebServiceImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapWebServiceImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapWebServiceImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapWebServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapWebServiceTest.webService.IDcardCheckResponse SoapWebServiceTest.webService.SoapWebServiceImpl.IDcardCheck(SoapWebServiceTest.webService.IDcardCheckRequest request) {
            return base.Channel.IDcardCheck(request);
        }
        
        public string IDcardCheck(string IDNum) {
            SoapWebServiceTest.webService.IDcardCheckRequest inValue = new SoapWebServiceTest.webService.IDcardCheckRequest();
            inValue.IDNum = IDNum;
            SoapWebServiceTest.webService.IDcardCheckResponse retVal = ((SoapWebServiceTest.webService.SoapWebServiceImpl)(this)).IDcardCheck(inValue);
            return retVal.IDcardCheckReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapWebServiceTest.webService.IDcardCheckResponse> SoapWebServiceTest.webService.SoapWebServiceImpl.IDcardCheckAsync(SoapWebServiceTest.webService.IDcardCheckRequest request) {
            return base.Channel.IDcardCheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapWebServiceTest.webService.IDcardCheckResponse> IDcardCheckAsync(string IDNum) {
            SoapWebServiceTest.webService.IDcardCheckRequest inValue = new SoapWebServiceTest.webService.IDcardCheckRequest();
            inValue.IDNum = IDNum;
            return ((SoapWebServiceTest.webService.SoapWebServiceImpl)(this)).IDcardCheckAsync(inValue);
        }
    }
}
